### ISSUE TITLE
Error with Python SDK: missing field `secretComment` at line 1 column 595

### ISSUE THREAD

**Issue by digitalghost-dev** [Infisical/sdk#46]
Here is what I am trying run with Python `v3.12`:
```python
from infisical_client import ClientSettings, InfisicalClient, AuthenticationOptions, UniversalAuthMethod, GetSecretOptions

client = InfisicalClient(ClientSettings(
    auth=AuthenticationOptions(
      universal_auth=UniversalAuthMethod(
        client_id="id",
        client_secret="id",
      )
    )
))

secret = client.getSecret(options=GetSecretOptions(
    environment="prod",
    project_id="id",
    secret_name="POSTGRES_CONNECTION_STRING"
))
value = secret.secret_value # get its value

print(value)
```

Error:
```bash
/Users/cs/PycharmProjects/pokemon-data-engineering/.venv/bin/python /Users/cs/PycharmProjects/pokemon-data-engineering/secret.py 
Traceback (most recent call last):
  File "/Users/cs/PycharmProjects/pokemon-data-engineering/secret.py", line 12, in <module>
    secret = client.getSecret(options=GetSecretOptions(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cs/PycharmProjects/pokemon-data-engineering/.venv/lib/python3.12/site-packages/infisical_client/infisical_client.py", line 42, in getSecret
    result = self._run_command(Command(get_secret=options))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cs/PycharmProjects/pokemon-data-engineering/.venv/lib/python3.12/site-packages/infisical_client/infisical_client.py", line 36, in _run_command
    raise Exception(response["errorMessage"])
Exception: error decoding response body: missing field `secretComment` at line 1 column 595
```

**Comment by maidul98** [comment]
Hey @digitalghost-dev , this issue has been fixed a few hours ago. Can you confirm if it works as expected for you?

**Comment by digitalghost-dev** [comment]
Hi, @maidul98 - just tried it again and still having the same issue. Is there something I need to do specifically?

**Comment by vmatsiiako** [comment]
hi @digitalghost-dev! Which version of the SDK are you running?

**Comment by digitalghost-dev** [comment]
Hey @vmatsiiako ! I just started using this 2 days ago so I'm on `v2.3.1`.

**Comment by maidul98** [comment]
Are you on self hosted or Infisical cloud @digitalghost-dev ?

**Comment by digitalghost-dev** [comment]
Okay, thank you @maidul98

**Comment by maidul98** [comment]
The patch is being deployed for this. Can you please try again once this action is complete? https://github.com/Infisical/infisical/actions/runs/10266363376/job/28405017790
